### ISSUE TITLE
CHScrobbler detects what I'm playing, but doesn't save the track to last.fm

### ISSUE THREAD

**Issue by Noahffiliation** [angelolz/CHScrobbler#32] opened 2023-08-30 04:39 UTC
CHScrobbler recognizes the track I'm playing in the game, last.fm shows I'm listening to the song, but once the track is over, it doesn't save to last.fm, it just goes from "Now playing X" to "Currently not playing anything!".

![image](https://github.com/angelolz/CHScrobbler/assets/26233268/d4fddc03-5472-4aa5-9e67-c497f7b24364)

**Comment by angelolz** [comment] 2023-08-30 15:57
Hmm.. The "Now Playing" message shouldn't show up every second.

Are you using the latest version of CHScrobbler?
Do you have the album set in your currently playing song text file?
Did you properly set your last.fm details? (It should warn you if you weren't successfully able to log in)

**Comment by Noahffiliation** [comment] 2023-08-31 19:48
I'm using the latest, v1.5. I did have the album set in `settings.ini`. I get the 'Successfully logged in with last.fm!' message when CHScrobbler starts.

As an experiment, I just tried running CHScrobbler v1.5 and Clone Hero without the `%b` in `settings.ini` and it worked just as expected, correctly scrobbled on last. fm.
![e4f3148a3c4706f7b4d4dc7948281cb4](https://github.com/angelolz/CHScrobbler/assets/26233268/a07ad0dc-1d2b-45ad-a425-4a1bea3c4b40)

**Comment by angelolz** [comment] 2023-09-06 22:52
Hmm, I haven't been able to recreate the issue. I've tried both with and without `%b`. Could you try adding `%b` in your `settings.ini` and start CHScrobbler again? CHScrobbler initializes the format of your now playing song on startup, so if that's changes, CHScrobbler needs to be restarted.

**Comment by Noahffiliation** [comment] 2023-09-06 23:06
Added `%b` in `settings.ini` and started a song

![image](https://github.com/angelolz/CHScrobbler/assets/26233268/09dddddf-3b88-457b-b9ae-709fb6037d8b)

**Comment by angelolz** [comment] 2023-09-06 23:36
Ah, I think I might know what the problem is. Could you add `%n` right before `%b`? CHScrobbler can't properly figure out the album name and starts acting up because your current song format looks like this:
```
Song
Artist
CharterAlbum Name
```

Hopefully that fixes it. I'll fix this in a future update to make sure that the `%n` is before `%b` in the formatting.

**Comment by Noahffiliation** [comment] 2023-09-07 06:10
Yup, that was it, working just as intended

**Comment by angelolz** [comment] 2023-09-09 17:02
Awesome! On that note, I'll be closing this issue now. Feel free to make a new issue if you discover another problem with the app!

**Closed by angelolz** 2023-09-09 17:02 UTC

**Comment by machinemessiah** [comment] 2023-09-14 01:41
> Awesome! On that note, I'll be closing this issue now. Feel free to make a new issue if you discover another problem with the app!

Might be a very stupid question, but is there any particular reason why a regular expression couldn't solve the issue here (regardless of what order the components of the string are in)?
